### ISSUE TITLE
USB RFID Reader support. 

### ISSUE THREAD

**Issue by mecaz** [tinkerthon/volumio-rfid#1]
Hello,

I want to make a project that playing spotify playlist on volumio via RFID cards. but unfortunately i coudnt make it, 
i have theese two card reader
1- https://www.aliexpress.com/item/33030536662.html?src=google&src=google&albch=shopping&acnt=494-037-6276&isdl=y&slnk=&plac=&mtctp=&albbt=Google_7_shopping&aff_platform=google&aff_short_key=UneMJZVf&&albagn=888888&albcp=6459716145&albag=79902878520&trgt=743612850714&crea=tr33030536662&netw=u&device=c&albpg=743612850714&albpd=tr33030536662&gclid=EAIaIQobChMIyb77jtjY6AIVgevtCh2KtwThEAYYAiABEgIMsvD_BwE&gclsrc=aw.ds
2- https://www.aliexpress.com/item/4000055560018.html?src=google&src=google&albch=shopping&acnt=494-037-6276&isdl=y&slnk=&plac=&mtctp=&albbt=Google_7_shopping&aff_platform=google&aff_short_key=UneMJZVf&&albagn=888888&albcp=9593689418&albag=102574444201&trgt=296904913880&crea=tr4000055560018&netw=u&device=c&albpg=296904913880&albpd=tr4000055560018&gclid=EAIaIQobChMI18yAlNjY6AIVw7TtCh0WFg56EAYYAiABEgI2WvD_BwE&gclsrc=aw.ds

can i use this readers with your code. can you help me please. i couldnt make it. 
Regards.

**Comment by oschettler** [comment]
Hi, I am by no means an expert in these devices. However, I very much doubt that it will work as my code specifically uses the SimpleMFRC522 library.
